//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Industrial
{
    [Serializable]
    public class RobotModeMsg : Message
    {
        public const string k_RosMessageName = "industrial_msgs/RobotMode";
        public override string RosMessageName => k_RosMessageName;

        //  The Robot mode message encapsulates the mode/teach state of the robot
        //  Typically this is controlled by the pendant key switch, but not always
        public sbyte val;
        //  enumerated values
        public const sbyte UNKNOWN = -1; //  Unknown or unavailable
        public const sbyte MANUAL = 1; //  Teach OR manual mode
        public const sbyte AUTO = 2; //  Automatic mode

        public RobotModeMsg()
        {
            this.val = 0;
        }

        public RobotModeMsg(sbyte val)
        {
            this.val = val;
        }

        public static RobotModeMsg Deserialize(MessageDeserializer deserializer) => new RobotModeMsg(deserializer);

        private RobotModeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.val);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.val);
        }

        public override string ToString()
        {
            return "RobotModeMsg: " +
            "\nval: " + val.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
