//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Industrial
{
    [Serializable]
    public class ServiceReturnCodeMsg : Message
    {
        public const string k_RosMessageName = "industrial_msgs/ServiceReturnCode";
        public override string RosMessageName => k_RosMessageName;

        //  Service return codes for simple requests.  All ROS-Industrial service
        //  replies are required to have a return code indicating success or failure
        //  Specific return codes for different failure should be negative.
        public sbyte val;
        public const sbyte SUCCESS = 1;
        public const sbyte FAILURE = -1;

        public ServiceReturnCodeMsg()
        {
            this.val = 0;
        }

        public ServiceReturnCodeMsg(sbyte val)
        {
            this.val = val;
        }

        public static ServiceReturnCodeMsg Deserialize(MessageDeserializer deserializer) => new ServiceReturnCodeMsg(deserializer);

        private ServiceReturnCodeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.val);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.val);
        }

        public override string ToString()
        {
            return "ServiceReturnCodeMsg: " +
            "\nval: " + val.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
