//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Industrial
{
    [Serializable]
    public class CmdJointTrajectoryRequest : Message
    {
        public const string k_RosMessageName = "industrial_msgs/CmdJointTrajectory";
        public override string RosMessageName => k_RosMessageName;

        //  Send a JointTrajectory command to the robot.
        //    - duplicates functionality of the joint_path_command topic
        //    - provides a response-code to verify command was received
        //    - returns when trajectory is sent to robot, not when motion completed
        //    - return code may NOT indicate successful transfer to robot
        public Trajectory.JointTrajectoryMsg trajectory;

        public CmdJointTrajectoryRequest()
        {
            this.trajectory = new Trajectory.JointTrajectoryMsg();
        }

        public CmdJointTrajectoryRequest(Trajectory.JointTrajectoryMsg trajectory)
        {
            this.trajectory = trajectory;
        }

        public static CmdJointTrajectoryRequest Deserialize(MessageDeserializer deserializer) => new CmdJointTrajectoryRequest(deserializer);

        private CmdJointTrajectoryRequest(MessageDeserializer deserializer)
        {
            this.trajectory = Trajectory.JointTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "CmdJointTrajectoryRequest: " +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
