//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Industrial
{
    [Serializable]
    public class GetRobotInfoRequest : Message
    {
        public const string k_RosMessageName = "industrial_msgs/GetRobotInfo";
        public override string RosMessageName => k_RosMessageName;

        //  The Get Robot Info service returns vendor specific information about
        //  the robot(s) connected by the driver

        public GetRobotInfoRequest()
        {
        }
        public static GetRobotInfoRequest Deserialize(MessageDeserializer deserializer) => new GetRobotInfoRequest(deserializer);

        private GetRobotInfoRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetRobotInfoRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
