//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Industrial
{
    [Serializable]
    public class GetRobotInfoResponse : Message
    {
        public const string k_RosMessageName = "industrial_msgs/GetRobotInfo";
        public override string RosMessageName => k_RosMessageName;

        public DeviceInfoMsg controller;
        public DeviceInfoMsg[] robots;
        public ServiceReturnCodeMsg code;

        public GetRobotInfoResponse()
        {
            this.controller = new DeviceInfoMsg();
            this.robots = new DeviceInfoMsg[0];
            this.code = new ServiceReturnCodeMsg();
        }

        public GetRobotInfoResponse(DeviceInfoMsg controller, DeviceInfoMsg[] robots, ServiceReturnCodeMsg code)
        {
            this.controller = controller;
            this.robots = robots;
            this.code = code;
        }

        public static GetRobotInfoResponse Deserialize(MessageDeserializer deserializer) => new GetRobotInfoResponse(deserializer);

        private GetRobotInfoResponse(MessageDeserializer deserializer)
        {
            this.controller = DeviceInfoMsg.Deserialize(deserializer);
            deserializer.Read(out this.robots, DeviceInfoMsg.Deserialize, deserializer.ReadLength());
            this.code = ServiceReturnCodeMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.controller);
            serializer.WriteLength(this.robots);
            serializer.Write(this.robots);
            serializer.Write(this.code);
        }

        public override string ToString()
        {
            return "GetRobotInfoResponse: " +
            "\ncontroller: " + controller.ToString() +
            "\nrobots: " + System.String.Join(", ", robots.ToList()) +
            "\ncode: " + code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
