//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Industrial
{
    [Serializable]
    public class SetDrivePowerResponse : Message
    {
        public const string k_RosMessageName = "industrial_msgs/SetDrivePower";
        public override string RosMessageName => k_RosMessageName;

        public ServiceReturnCodeMsg code;

        public SetDrivePowerResponse()
        {
            this.code = new ServiceReturnCodeMsg();
        }

        public SetDrivePowerResponse(ServiceReturnCodeMsg code)
        {
            this.code = code;
        }

        public static SetDrivePowerResponse Deserialize(MessageDeserializer deserializer) => new SetDrivePowerResponse(deserializer);

        private SetDrivePowerResponse(MessageDeserializer deserializer)
        {
            this.code = ServiceReturnCodeMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.code);
        }

        public override string ToString()
        {
            return "SetDrivePowerResponse: " +
            "\ncode: " + code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
