//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Industrial
{
    [Serializable]
    public class StopMotionRequest : Message
    {
        public const string k_RosMessageName = "industrial_msgs/StopMotion";
        public override string RosMessageName => k_RosMessageName;

        //  Stops current robot motion.  Motion resumed by using start_motion service
        //  or by sending a new motion command

        public StopMotionRequest()
        {
        }
        public static StopMotionRequest Deserialize(MessageDeserializer deserializer) => new StopMotionRequest(deserializer);

        private StopMotionRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "StopMotionRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
